#!/usr/bin/env bash

set -e

test -v ${TAILSCALE_AUTH_KEY}

up() {
  sleep 5

  tailscale up \
    -accept-dns=${TAILSCALE_ACCEPT_DNS:-true} \
    -accept-routes=${TAILSCALE_ACCEPT_ROUTES:-false} \
    -advertise-routes=${TAILSCALE_ADVERTISE_ROUTES} \
    -advertise-tags=${TAILSCALE_ADVERTISE_TAGS} \
    -authkey=${TAILSCALE_AUTH_KEY} \
    -force-reauth=${TAILSCALE_FORCE_REAUTH:-false} \
    -host-routes=${TAILSCALE_HOST_ROUTES:-true} \
    -hostname=${TAILSCALE_HOSTNAME:-$(hostname)} \
    -login-server=${TAILSCALE_LOGIN_SERVER:-"https://login.tailscale.com"} \
    -netfilter-mode=${TAILSCALE_NETFILTER_MODE:-on} \
    -shields-up=${TAILSCALE_SHIELDS_UP:-false} \
    -snat-subnet-routes-mode=${TAILSCALE_SNAT_SUBNET_ROUTES:-true}
}

if [ ! -d /dev/net ]; then mkdir /dev/net; fi
if [ ! -e /dev/net/tun ]; then mknod /dev/net/tun c 10 200; fi

up & tailscaled
